### ISSUE TITLE
upgrading to rails 4.0.1 breaks create()

### ISSUE THREAD

**Issue by smooshy** [thoughtbot/factory_bot_rails#115]
Upgraded to rails 4.0.1 and all of a sudden most of my tests break like this: 

```
Failure/Error: let(:project) { create(:project) }
     NoMethodError:
       undefined method `[]' for nil:NilClass
```

factory_girl_rails, 4.2.1
factory_girl, 4.2.0

**Comment by benjaminwood** [comment]
+1

`Installing protected_attributes 1.0.9 (was 1.0.3)` == solved!
