### ISSUE TITLE
Quitting template usage is wrong

### ISSUE THREAD

**Issue by dima4p** [thoughtbot/factory_bot_rails#147]
1. Standard rails generator behavior is asking the action in the case the file exists. So the generator should not check for the existence.
2. Quitting template usage breaks the use of more sophisticated templates like mine `factory_girl_fixtures_template`.
3. Quitting template usage breaks the standard rails generators workflow.
4. The factory generated with the new code is buggy breaking the ruby style.

So, please, restore back the templates directory in the gem and use of it so that the people that use custom templates for the FG, can continue explore them in the latest versions.

**Comment by composerinteralia** [comment]
https://github.com/thoughtbot/factory_bot_rails/pull/193
