### ISSUE TITLE
rails generate factory_girl:model no longer uses factory_girl/model/fixtures.erb file?

### ISSUE THREAD

**Issue by dannyvanhoof** [thoughtbot/factory_bot_rails#148]
I have the impression that pull request "Do not generate new file if `factories.rb` exists #135" also removed the possibility to have a custom fixtures.erb file in a project's lib/templates/factory_girl/model folder, as it used to be:

file lib/generators/factory_girl/model/model_generator.rb

```
      def create_fixture_file
  -        filename = [table_name, filename_suffix].compact.join('_')
  -        template 'fixtures.erb', File.join(options[:dir], "#{filename}.rb")
  +        if File.exist?(factories_file)
  +          insert_factory_into_existing_file
  +        else
  +          create_factory_file
  +        end
       end
```

**Comment by danlaffan** [comment]
+1

What is the situation here - is the custom template generator gone for good or is it available elsewhere?
