### ISSUE TITLE
require: false ?

### ISSUE THREAD

**Issue by alepore** [thoughtbot/factory_bot_rails#162]
I just got this exact problem during a `rake db:setup` and solved in the explained way: http://stackoverflow.com/questions/12423273/factorygirl-screws-up-rake-dbmigrate-process

Should we maybe suggests that `require` method in the README to avoid similar problems?

**Comment by betesh** [comment]
Related to  #192

Another option is to avoid loading FactoryGirl when factory_girl_rails' railtie is loaded.

**Comment by betesh** [comment]
If @thoughtbot approves of making that change, I'll open a PR

**Comment by composerinteralia** [comment]
Adding `require: false` disables the generator, so I wouldn't want to add it to the README.

Most of the problems with loading the factory definitions in the Railtie are related to static attributes (#192 may be an exception, so I will leave that issue open), which we are planning to deprecate in https://github.com/thoughtbot/factory_bot/pull/1135.

Thanks for the report!
