### ISSUE TITLE
Quick Start Download & Config Missing Require

### ISSUE THREAD

**Issue by megsvetz** [thoughtbot/factory_bot_rails#169]
In your quick start/download section you forget to mention adding the following to your spec_helper file when using with RSpec:

require 'factory_girl_rails'

Thanks!

**Comment by composerinteralia** [comment]
Thanks for letting us know. In the latest versions of `rails` and `rspec-rails` you shouldn't need to require `factory_bot_rails`. The `spec/rails_helper.rb` loads your rails application, which automatically loads all of your gems. Feel free to reopen the issue if you are still having problems.
