### ISSUE TITLE
Difficult to access engine factories from main application

### ISSUE THREAD

**Issue by crystalneth** [thoughtbot/factory_bot_rails#180]
I spent a lot of time tracking down how to do this, and the method I found seems obscure and wrong.

I want to use an engine's factories within the main application, e.g. FactoryGirl.create(:engine_product).

Adding to the engine gem's files and test_files does not help. I could not figure out how to to require the factory files.

Ultimately, I ended up adding what's below to the engine file, something I tracked down buried in a merge comment. Should there be a more supported way of exposing engine factories?

``` ruby
    initializer "engine.factories", :after => "factory_girl.set_factory_paths" do
      FactoryGirl.definition_file_paths << File.expand_path('../../../spec/factories', __FILE__) if defined?(FactoryGirl)
    end
```

**Comment by composerinteralia** [comment]
https://github.com/thoughtbot/factory_bot_rails/pull/149 adds this to the README

**Comment by composerinteralia** [comment]
Closing this issue, since we added a new configuration option (documented in the README) for fbr 5 that should make this easier.
