### ISSUE TITLE
find_definitions is loading test code in development

### ISSUE THREAD

**Issue by betesh** [thoughtbot/factory_bot_rails#192]
Some of our factories (in `spec/factories/`) contain code that modifies our model definitions.

There are a few reasons we do this:
- Some functionality is only needed in factories (setting a private attribute directly without resorting to metaprogramming)
- Some DB tables don't have any ActiveRecord model class because we only interface with them via java (We are using jRuby)

Such code is not intended to be loaded in development mode and when it is loaded, it actually interferes with definitions (or absence of definitions) in `app/models`.

However, it **is** being loaded by [FactoryGirl::Railtie](https://github.com/thoughtbot/factory_girl_rails/blob/v4.6.0/lib/factory_girl_rails/railtie.rb#L21).

We are using this monkey-patch (with rails 3.2, factory_girl_rails 4.3.0) to make factory_girl_rails only be loaded when running a generator:

```
# Gemfile
 group :development do
   gem "factory_girl_rails", require: false
 end


# config/initializers/factory_girl_rails.rb
class ::Rails::Engine
  def load_generators_with_factory_girl_rails(app=self)
    require "factory_girl_rails"
    # Note that it's a little late to be loading the gem,
    # as initializers have already run.
    # So we need to run the initializer ourselves.
    FactoryGirl::Railtie.instance.run_initializers(:default, Rails.application)
    load_generators_without_factory_girl_rails(app)
  end

  alias_method_chain :load_generators, :factory_girl_rails
end
```

However, the ideal solution would be to make the after_initialize block in the railtie conditional on whether a generator is running.

**Comment by composerinteralia** [comment]
Closing this issue, since we added a new configuration option that will allow you to avoid loading factory definitions for cases like this.
