### ISSUE TITLE
Start service rails s

### ISSUE THREAD

**Issue by B0Dim** [thoughtbot/factory_bot_rails#205]
Hi anybody,

I have error when I start service: rails s
Error:
=> Booting Puma
=> Rails 4.2.5.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/home/dim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/factory_girl_rails-4.6.0/lib/factory_girl_rails/railtie.rb:13:in `block in <class:Railtie>': undefined method`definition_file_paths=' for FactoryGirl:Module (NoMethodError)

How I can fix it?

**Comment by Ashviniv** [comment]
@B0Dim Try adding version of factory_girl in the `Gemfile` like ` gem 'factory_girl_rails', '~> 4.2'`.
For more details you can refer to the issue in the closed issues.[Issue 14](https://github.com/thoughtbot/factory_girl_rails/issues/14).

**Comment by composerinteralia** [comment]
I'm going to assume that fixed it 😄
