### ISSUE TITLE
Building the factory with the key "attributes"

### ISSUE THREAD

**Issue by ArturMinnullin** [thoughtbot/factory_bot_rails#219]
Hey,

I try to parse the response from stripe and create the following presenter for these purposes:

```
class PlanPresenter
  attr_reader :id, :name, :about, :amount, :duration

  def initialize(json)
    @id = json["id"]
    @name = json["attributes"]["name"]
    @about = json["attributes"]["about"]
    @amount = json["attributes"]["amount"]
    @duration = json["attributes"]["duration"]
  end
end
```

For the tests I want to write the factory that will generate the instance of this class:

```
FactoryGirl.define do
  factory :customer_plan, class: PlanPresenter do
    id { Faker::Internet.slug }
    price { rand(30) }
    add_attribute(:attributes) do
      {
        name: "Name",
        about: "About",
        amount: 123,
        duration: "month"
      }
    end

    initialize_with { new(attributes.stringify_keys) }
  end
end
```

However, it doesn't work. I'm getting `SystemStackError: stack level too deep`. Is it possible to generate the Hash with the key "attributes"?

**Comment by composerinteralia** [comment]
Thanks! I opened https://github.com/thoughtbot/factory_bot/issues/1155 to track this. The way things are now you cannot refer to `attributes` inside `initialize_with`.
