### ISSUE TITLE
ArgumentError with Rails 5.1

### ISSUE THREAD

**Issue by brunowego** [thoughtbot/factory_bot_rails#228]
After update for Rails version 5.1 I get strange error:

```sh
ArgumentError: wrong number of arguments (given 1, expected 0)
```

My `Gemfile` have this changes:

```
...
gem 'rails', github: 'rails/rails'
gem 'arel', github: 'rails/arel'
...
```

The error happen when I try use:

```rb
FactoryGirl.create :user, :confirmed
```

Maybe an error in Rails 5.1.

**Comment by jfornoff** [comment]
Can confirm, saw the same thing in 5.1.0.beta1, but also with other numbers of arguments (e.g., given 3, expected 4).

**Comment by joshuaclayton** [comment]
@brunowego @jfornoff can either of you provide backtraces here, or provide a Rails app that reproduces this?

**Comment by jfornoff** [comment]
Hi Josh,

unfortunately, my test suite did not provide any backtraces, just pointed to occurrences of create(:model_name) in the spec files themselves. App is proprietary and I can't share it :-(

**Comment by joshuaclayton** [comment]
@jfornoff ah, bummer - are you able to put together a *tiny* app that demonstrates the bug? Without a backtrace, it's impossible to tell if it's an issue with FG, ActiveRecord, or any number of other layers here.

**Comment by jfornoff** [comment]
I'll try and get back to you!

**Comment by jfornoff** [comment]
@joshuaclayton Ayyy, forgot i had Gems squelched from my backtraces!

      ArgumentError:
        wrong number of arguments (given 3, expected 4)
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/paranoia-2.2.1/lib/paranoia.rb:272:in `build_relation'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/validations/uniqueness.rb:17:in `validate_each'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activemodel-5.1.0.beta1/lib/active_model/validator.rb:150:in `block in validate'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activemodel-5.1.0.beta1/lib/active_model/validator.rb:147:in `each'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activemodel-5.1.0.beta1/lib/active_model/validator.rb:147:in `validate'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:413:in `block in make_lambda'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:600:in `catch'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:600:in `block in default_terminator'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:198:in `block in halting'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:507:in `block in invoke_before'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:507:in `each'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:507:in `invoke_before'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:130:in `run_callbacks'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:825:in `_run_validate_callbacks'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activemodel-5.1.0.beta1/lib/active_model/validations.rb:405:in `run_validations!'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activemodel-5.1.0.beta1/lib/active_model/validations/callbacks.rb:110:in `block in run_validations!'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:131:in `run_callbacks'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activemodel-5.1.0.beta1/lib/active_model/validations/callbacks.rb:110:in `run_validations!'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activemodel-5.1.0.beta1/lib/active_model/validations.rb:335:in `valid?'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/validations.rb:65:in `valid?'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/validations.rb:82:in `perform_validations'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/validations.rb:50:in `save!'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/transactions.rb:313:in `block in save!'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/transaction.rb:186:in `within_new_transaction'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/transactions.rb:210:in `transaction'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/transactions.rb:313:in `save!'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activerecord-5.1.0.beta1/lib/active_record/suppressor.rb:46:in `save!'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/configuration.rb:18:in `block in initialize'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/evaluation.rb:15:in `create'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `tap'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `result'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/factory.rb:42:in `run'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/notifications.rb:166:in `instrument'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:28:in `run'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/strategy/build.rb:5:in `association'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/evaluator.rb:33:in `association'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/attribute/association.rb:19:in `block in to_proc'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/evaluator.rb:77:in `instance_exec'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/evaluator.rb:77:in `block in define_attribute'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:56:in `get'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/evaluation.rb:12:in `object'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/strategy/build.rb:9:in `result'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/factory.rb:42:in `run'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/activesupport-5.1.0.beta1/lib/active_support/notifications.rb:166:in `instrument'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:28:in `run'
      # /home/wrkfan/.rvm/gems/ruby-2.4.0@qgen/gems/factory_girl-4.8.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
      # ./spec/models/qgen/survey_spec.rb:22:in `block (4 levels) in <top (required)>'

Apparently its somehow related to `paranoia` (gem for implementing soft-deletion of records).
So I'm not entirely sure what in which domain this is going bad, I'll try and look into the Gem, but I suspect you're way better than me with Rails internals, maybe it jumps out at you right away!

**Comment by jfornoff** [comment]
It's a change in ActiveModel, IMO. 

[Here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validator.rb#L150
). validate_each now takes 3 arguments instead of four, and `paranoia` has overwritten the Uniqueness Validator of ActiveRecord. They've already fixed it, too! The next gem release of `paranoia` should fix this issue. 

I think there's nothing to be done from your side, thanks for taking the time @joshuaclayton! :100:

**Comment by joshuaclayton** [comment]
@jfornoff ah, thanks for following up, and good to know!

@brunowego are you also using the paranoia gem, per chance (or something else related to uniqueness validations w/AR)? If so, mind confirming here and closing this out so others who run across this know where they might look?

**Comment by brunowego** [comment]
Sorry for the delay. No, I not using paranoia gem. Take a look at my Gemfile:

```rb
# frozen_string_literal: true
source 'https://rubygems.org'
ruby '2.3.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.19'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 3.3'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.11'
gem 'knock', '~> 2.1.1'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'rack-cors', '~> 0.4.1'

gem 'apartment', '~> 1.2.0'
gem 'apartment-sidekiq', '~> 1.1.0'

gem 'pundit', '~> 1.1.0'
gem 'rolify', '~> 5.1.0'

gem 'image_processing', '~> 0.4.1'
gem 'mini_magick', '~> 4.6.1'
gem 'shrine', '~> 2.5.0'

gem 'aasm', '~> 4.11.1'
gem 'active_model_serializers', '~> 0.10.4'
gem 'ancestry', '~> 2.2.2'
gem 'money-rails', '~> 1.8.0'
gem 'rack-attack', '~> 5.0.1'
gem 'rails-i18n', '~> 5.0.3'
gem 'searchkick', '~> 2.1.1'
gem 'sidekiq', '~> 4.2.9'
gem 'whenever', '~> 0.9.7'

gem 'rollbar', '~> 2.14.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger
  # console
  gem 'byebug', platform: :mri

  gem 'dotenv-rails', '~> 2.2.0'
  gem 'pgreset', '~> 0.1.1'

  gem 'factory_girl_rails', '~> 4.8.0'
  gem 'faker', '~> 1.7.3'
  gem 'rspec-rails', '~> 3.5.2'
  gem 'shoulda-matchers', '~> 3.1.1'
  gem 'simplecov', '~> 0.13.0'
end

group :development do
  gem 'bullet', '~> 5.5.0'
  gem 'listen', '~> 3.1.5'
  # Spring speeds up development by keeping your application running in the
  # background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by MyExperiments** [comment]
@brunowego Were you able to fix this? I am also having the same issue. Any help will be appreciated.

**Comment by brunowego** [comment]
@MyExperiments no. Sorry.

**Comment by qsona** [comment]
@brunowego Hi, I faced the same problem, but after upgrading bullet from 5.5.0 to 5.5.1, it becomes fine.

**Comment by andreleoni** [comment]
Here update the bullet gem from 5.4.0 to 5.5.1 version works fine too @brunowego

**Comment by composerinteralia** [comment]
It seems like this problem was coming from some other gems, so I am going to close for now. Feel free to reopen if this comes up again. Thanks!

**Comment by joshuapinter** [comment]
Just adding a tidbit here. In our case, our `paranoia` gem was updated to master but we were also using the `paranoia_uniqueness_validator` gem, which was out of date. It needed to be updated to >= 3.1 .
