### ISSUE TITLE
Putting namespaced factories into separate folder

### ISSUE THREAD

**Issue by tomdracz** [thoughtbot/factory_bot_rails#231]
Currently when I create factory for model Foo::Bar it will create a file in spec/factories (or whatever my dir is) named foo_bars.rb
Rspec generator will create spec/models/foo/bar_spec.rb
Is it useful to have option (or default to) putting namespaced factories into folders?

Currently we just use table_name when assigning a file name as per https://github.com/thoughtbot/factory_girl_rails/blob/master/lib/generators/factory_girl/model/model_generator.rb#L77-L83

What are the thoughts of changing that to something following RSpec convention, in effect, something along the lines of:

```
def filename
  if factory_girl_options[:filename_proc].present?
    factory_girl_options[:filename_proc].call(table_name)
  else
    [File.join(class_path, plural_name), filename_suffix].compact.join('_')
  end
end
```

This would result in the example above being created in spec/factories/foo/bars.rb

Any thoughts on that? I'd be happy to provide PR but would like the thoughts on the best approach.
- Having it as a new default?
- Passing it as factory_girl_options[:namespaced] and if the option is true, use namespaced folders? Would ignore filename_proc option then
- Any other ideas?

**Comment by composerinteralia** [comment]
I know it has been a while, but this seems like a reasonable change to me. Are you still interested in making a PR? I don't think we need an option for this; the namespace makes sense as the new default. We can introduce an option if the new default turns out to be a problem for someone.
