### ISSUE TITLE
Question/Feature: traits that allow controlling associations

### ISSUE THREAD

**Issue by Epigene** [thoughtbot/factory_bot_rails#237]
Hi.

I have fallen in love with `transient` attributes and lately have been writing traits that control associations.
Here is a simple example. Say we have a `User` model that can have many `Post`s. I would find it useful to write a trait for User that also makes a post in one go.

```rb
FactoryGirl.create(:user, :with_post, post_factory_options: {traits: [], attributes: {}})
``` 

and the trait

```rb
# uses transient :post_factory_options 
trait :with_post do
  transient do
    post_factory_options {}
   end
     
  after(:create) do |user, evaluator|
    options = {
      user: user
    }.merge(evaluator.post_factory_options[:attributes] || {})
       
    FactoryGirl.create(*[:association, *(evaluator.post_factory_options.traits || [])], options)
  end
end
``` 

A structure like this allows nesting the `*_factory_options` keys, provided needed factories and traits exist to use them.

I am tempted to write some introspecting, metaprogramming code that would automagically define association traits on Rails model factories. It could even be a gem.

My question are:

1. Would this be worthwhile? Perhaps something like this already exists?
2. Can model factories reliably introspect what associations are defined on the model?
3. Where could I look for ways to have a gem define traits programmatically (look up what factories are defined in the using codebase)?

**Comment by composerinteralia** [comment]
Thanks for the issue. Better support for collection associations is definitely something I am thinking about. Since this is more a factory_bot issue than a factory_bot_rails issue, and we have some related issues on that repo, I am going to close this issue.
