### ISSUE TITLE
Improve "Trait not registered" details

### ISSUE THREAD

**Issue by hakunin** [thoughtbot/factory_bot_rails#249]
I had this pop up on me today:

```
     Failure/Error:
       FactoryGirl.create(:project_link, {
         project_id: project.id,
       })

     ArgumentError:
       Trait not registered: organization
```

Okay.. I know `project_link` doesn't have organization so the problem is going to be somewhere else.

Drilling down into my factories:

    FactoryGirl.define do
      factory :project_link do
        project { FactoryGirl.create(:account_project) }
        organization_link
        sequence(:remote_project_id)
      end
    end

Yeah, no organization here, let's look at `organization_link`

    FactoryGirl.define do
      factory :organization_link do
        sequence(:remote_organization_id)
        organization # <- problem here?
        client_application
      end
    end

Can you see whats wrong wit this factory? 
Since the organization_id column is there, I couldn't either.

Turns out, I had named the factory for organization something else, since I have two different organization factories, so it had to be `organization { FB.create(:product_organization) }`.

Now lets analyse what happened here:

- FB reported an issue, but didn't tell me *where* it is from (while it tried to point to the original factory, which didn't have any issue)
- The message said the trait isn't registered, which wasn't true, since the organization line was there
- It didn't tell me I had no factory called organization, or that the organization line was wrong

While I was able to find the cause quickly, I have no doubt this would take newbs for a ride, so I'd like to take this opportunity to report on the 3 above UX issues that could be improved.

It would be probably good to create 3 improvement issues with `help wanted` tag and reference and close this one.

**Comment by composerinteralia** [comment]
Thanks for the issue. I have opened https://github.com/thoughtbot/factory_bot/issues/1221 and https://github.com/thoughtbot/factory_bot/issues/1222 on factory_bot to cover these.
