### ISSUE TITLE
Configuring directory does not work in engine

### ISSUE THREAD

**Issue by asoong** [thoughtbot/factory_bot_rails#251]
Inside my engine, i'm trying to change the directory for factories:

```
config.generators do |g|
  g.factory_bot dir: 'spec/factories'
end
```

The path should be `spec/factories` but when it goes to `find_definitions`, it still looks inside `spec/dummy/spec/factories`. Any ideas?

**Comment by composerinteralia** [comment]
I think I would need a bit more context to help here. Can you link to a sample app that demonstrates the bug?

**Comment by asoong** [comment]
This is no longer an issue. Thank you for taking a look.
