### ISSUE TITLE
Customizing template for generating spec/factories/model_name.rb

### ISSUE THREAD

**Issue by Kani999** [thoughtbot/factory_bot_rails#254]
Is there any way, how to customize a template which generates factories file?

The generated sample looks like this 

```
FactoryBot.define do
  factory :test_test_product do
    name "MyString"
    price "9.99"
  end
end
```

but I need to add one more line to this generator

```
FactoryBot.define do
  factory :test_test_product do
    name "MyString"
    price "9.99"
    audit_comment "audit sample"
  end
end
```
It's because I'am using gem `audited` https://github.com/collectiveidea/audited

**Comment by joshuaclayton** [comment]
@Kani999 there's no built-in way to update the generated factories file; your best bet is, for the models that need to be audited, adding the fields explicitly (in the case where the fields are required).
