### ISSUE TITLE
Please clarify the release policy

### ISSUE THREAD

**Issue by ge-fa** [thoughtbot/factory_bot_rails#256]
Hi all,

As per the rename, I would like to package factory_bot_rails for Debian. However, I'm confused:

- The tag v4.8.2, 2017/10/23, contained factory_bot_rails.
- The tag v4.9.0, 2017/10/23, contained factory_girl_rails.

Normally, for Debian packaging, a so called "watch" file is used, to check for the latest upstream release.
But in this case, this doesn't work properly, as the latest release is not about factory_bot_rails, but about factory_girl_rails.

Could you please clarify, what to expect in the future? In case there are further releases planned for factory_girl_rails, would it be possible to use different release naming schemes for girl_rails vs bot_rails?

Thanks for your work and all the best!

**Comment by composerinteralia** [comment]
Details here https://robots.thoughtbot.com/factory_bot

> all new changes will occur only on the factory_bot and factory_bot_rails gems

**Comment by odlp** [comment]
Apologies for the confusion here. I've just released / tagged factory_bot and factory_bot_rails version 4.10.0, which includes the rewind sequences feature.

Please feel free to reopen if this hasn't resolved the issue.
