### ISSUE TITLE
Issue using a factory named `trait`

### ISSUE THREAD

**Issue by extrajordanary** [thoughtbot/factory_bot_rails#257]
**The issue**
I have models named `Trait` and `UserTrait` and the generated factories started out like this:

```
FactoryBot.define do
  factory :trait do
    label "MyString"
    description "MyString"
  end
end

FactoryBot.define do
  factory :user_trait do
    user nil
    trait nil
  end
end
```

And when I removed the `nil`s to let FactoryBot infer the association to the factory with the same name, I got errors when running rspec. 
```
FactoryBot.define do
  factory :user_trait do
    user
    trait
  end
end
```

First error was this:
```
Failure/Error: trait

ArgumentError:
  wrong number of arguments (given 0, expected 1)
# /Users/Jordan/.rvm/gems/ruby-2.3.1/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:166:in `trait'
# ./spec/factories/user_traits.rb:4:in `block (2 levels) in <top (required)>'
...
```

and then every other spec file gave this error:
```
Failure/Error:
  factory :connection_request do
    user
    association :pending_ally, factory: :user
  end

FactoryBot::DuplicateDefinitionError:
  Factory already registered: connection_request
...
```

`connection_request` is the first of my factories alphabetically.

**The solution** 
Adding an explicit pointer to the trait factory:
```
FactoryBot.define do
  factory :user_trait do
    user
    trait factory: :trait
  end
end
```

So I guess I discovered that `trait` is a method name for something in FactoryBot, and somehow that first error caused it to try to reload all the factories, resulting in the duplicate definition error?

Not sure if maybe there could just be a check inside of factory definitions to first look for a factory called `trait` before using the other method by that name? Or at least throwing a warning of some kind.

I had changed about a dozen factories all at once to remove the default `nil`s so it took me awhile to realize the root issue (red herring was all the redefinition errors which distracted me from the now-obviously-more-helpful first error listed above).

**Comment by composerinteralia** [comment]
Yup, your trait association is conflicting with the [traits](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#traits) feature.

You can try using the [`association`](http://www.rubydoc.info/gems/factory_bot/FactoryBot/DefinitionProxy#association-instance_method) method directly: `association :trait, factory: :trait`

**Comment by composerinteralia** [comment]
Thanks for the issue! I am going to close this since it is more a factory_bot documentation issue than a factory_bot_rails issue. I opened https://github.com/thoughtbot/factory_bot/issues/1165 to track this.
