### ISSUE TITLE
Version 4.9.0 not present on Rubygems

### ISSUE THREAD

**Issue by PedroSena** [thoughtbot/factory_bot_rails#260]
Hey,

I noticed that the version 4.9.0 is properly tagged on this repository but no present on Rubygems(https://rubygems.org/gems/factory_bot_rails), I was expecting to see it there, am I missing something ?

Thanks

**Comment by mikegee** [comment]
I don't know, but here are a couple clues:

There is no significant changes in [the diff](https://github.com/thoughtbot/factory_bot_rails/compare/v4.8.2...v4.9.0). [The PR](https://github.com/thoughtbot/factory_bot_rails/pull/246) was closed instead of merged into master.

**Comment by mjankowski** [comment]
Similar question and more explanation here - https://github.com/thoughtbot/factory_bot_rails/issues/255

The gist of it is that the release tagged 4.9.0 is the latest (and probably last) release of `factory_girl_rails`. Separately (but, awkwardly using the same git repo) we have `factory_bot_rails` with 4.8.2 release tag as it's first release.

If you are using version 4.8.2 of factory_bot_rails, then you are on the (as of now!) latest version.

As a sort of side question here so we can understand how people are getting confused here ... can you walk through the steps of whatever upgrade or audit process you are in where you notice this disparity? I would think that for people doing periodic `bundle update` or similar workflows they would not even notice the release tags, and would just be hitting rubygems. Are you bundling to the git repo?

**Comment by PedroSena** [comment]
Thanks for the replies.

@mjankowski  The issue was not related to upgrade from factory_girls to factory_bot(I was already on factory_bot_rails) I just casually looked at the releases for the gem found 4.9.0 and was surprised that it was not present in Rubygems considering it was tagged few months ago.

**Comment by mjankowski** [comment]
No problem.

Hopefully this will be less confusing the next time we do a release and increment the f_b_r version to be (maybe) higher than the f_g_r version. Until then I've added some [release notes](https://github.com/thoughtbot/factory_bot_rails/releases) which maybe will help people out.
