### ISSUE TITLE
Release v4.9.0 to rubygems

### ISSUE THREAD

**Issue by jandudulski** [thoughtbot/factory_bot_rails#261]
Hi,

5 days ago you released version `v4.9.0` (at least - by tagging) but it's not pushed to rubygems, where version `v4.8.2` is still the latest one.

cc @mjankowski

**Comment by mjankowski** [comment]
Read more in https://github.com/thoughtbot/factory_bot_rails/issues/260 and https://github.com/thoughtbot/factory_bot_rails/issues/255

4.8.2 is currently the latest `factory_bot_rails` release. 4.9.0 is the latest (and likely last) `factory_girl_rails` release.
