### ISSUE TITLE
Add different objects to has_many association using traits while being usable with build and build_stubbed

### ISSUE THREAD

**Issue by kaipr** [thoughtbot/factory_bot_rails#262]
Hello, hope this is the right place to ask.

We have some instances where we need to dynamically add different objects to an `has_many` association and would like to do so in a way that works with both `build`/`create` and `build_stubbed`.

```ruby
factory :line_item do
  trait :with_foo_charge do
    after(:build) do |line_item, _evaluator|
      line_item.charges << build(:foo_charge)
    end
  end

  trait :with_bar_charge do
    after(:build) do |line_item, _evaluator|
      line_item.charges << build(:bar_charge)
    end
  end
end

# does what I want
build(:line_item, :with_foo_charge, :with_bar_charge)

# how do I get this to work
build_stubbed(:line_item, :with_foo_charge, :with_bar_charge)
```

Is there a clean way to achieve this? I could probably do it with a duplicated `after(:stub)` block, but I feel like there should be a better way I don't know of yet?

**Comment by composerinteralia** [comment]
Thanks for the issue. I'm going to close this, since it is more a factory_bot issue than a factory_bot_rails issue, and I think https://github.com/thoughtbot/factory_bot/issues/1150 is similar enough that we can track it there instead.
