### ISSUE TITLE
4.9.0 Gem Not Published to Rubygems

### ISSUE THREAD

**Issue by nrowegt** [thoughtbot/factory_bot_rails#267]
![image](https://user-images.githubusercontent.com/1641120/38573676-d27c8c3e-3cc4-11e8-9599-29963041379b.png)

**Comment by mikegee** [comment]
This issue is a duplicate of https://github.com/thoughtbot/factory_bot_rails/issues/261, https://github.com/thoughtbot/factory_bot_rails/issues/260, https://github.com/thoughtbot/factory_bot_rails/issues/255, and https://github.com/thoughtbot/factory_bot_rails/issues/250.
