### ISSUE TITLE
Why does FactoryBot.find_definitions automatically create data?

### ISSUE THREAD

**Issue by adambruss** [thoughtbot/factory_bot_rails#269]
We've tried using FactoryBotRails and plain old FactoryBot (no customization).  Why is this default behavior?  I can't think of a single use case where that would be needed.

We're using Ruby 2.3.1 and Rails 5.1

Thanks!

**Comment by composerinteralia** [comment]
Can you provide a bit more information? What do you mean by "automatically create data"? [`FactoryBot.find_definitions`](https://github.com/thoughtbot/factory_bot/blob/c716ce01b448ce4e0bf855c5a2c63ecb9206322e/lib/factory_bot/find_definitions.rb) just loads the files where your factories are defined. A factory definition on its own should not be creating any data.

**Comment by composerinteralia** [comment]
I'm going to close for now. Feel free to reopen with a bit more information if this is still an issue. Thanks!
