### ISSUE TITLE
Ruby 2.5.1 Environment Caching

### ISSUE THREAD

**Issue by mlh758** [thoughtbot/factory_bot_rails#292]
I've been working on upgrading several applications from Ruby 2.4.1 to Ruby 2.5.1. 4 of the 5 worked just fine but one of them is getting some strange errors that _seem_ to be tied to Factory Bot. The application itself runs just fine but I can't execute the test suite.

With factory_bot_rails 4.8.2 I was getting errors about all the factories already being registered and I noticed that my other apps were at 4.10.0 so I changed the Gemfile of the troubled app to 4.10.0 as well. That changed all my errors to:

```
An error occurred while loading ./spec/views/some_spec.rb...
Failure/Error: require_relative '../config/environment.rb'

RuntimeError:
  can't modify immutable cached environment
# ./config/environment.rb:7:in `<top (required)>'
# ./spec/rails_helper.rb:3:in `require_relative'
# ./spec/rails_helper.rb:3:in `<top (required)>'
```

The line in question in environment.rb is the seemingly benign `Rails.application.initialize!` and that line exists in all my apps and I'm pretty sure is typical Rails stuff. 

If I change `config.cache_classes = true` to false in my test environment all my errors flip back to factories already being registered.

The cache error seems to originate within [sprockets](https://github.com/rails/sprockets/blob/master/lib/sprockets/cached_environment.rb#L61) but only because something is trying to modify what should be an immutable cache. I've been comparing the applications and searching for calls to FactoryBot and I'm not seeing any differences in implementation between the apps. I'm stuck.

My factory files live under `spec/factories` in all the apps. rspec-core is at 3.7.1

**Comment by mlh758** [comment]
This was entirely my fault. Some of our factories had a deprecated block syntax, the errors from Rails were just misleading.

**Comment by composerinteralia** [comment]
I'm glad you figured it out! Do you think there is anything we could do either on our side or in Rails to make the error message more helpful?

**Comment by mlh758** [comment]
Anything that indicated there was a syntax error, or any kind of error in the factory files, would have made troubleshooting far easier.

**Comment by mlh758** [comment]
I think it was invalid Ruby syntax that was just being accepted for some reason when I was still on Ruby 2.4.1. It looked like:
`sequence :something { |n| n }`

Fixing it was just
`sequence(:something) { |n| n }`

It seems like issue was that the files outright failed to load, the errors that got dropped into the console though were what I mentioned above so they pointed me in a different direction.

**Comment by sshaw** [comment]
I had this issue too running `rspec spec/models`. When I ran `rspec spec/models/user_spec.rb` I saw the syntax error with blocks. 

I suppose Rails hits an odd path when the file can't load. Had me scratchin' my head for a few.
