### ISSUE TITLE
config.factory_bot.definition_file_paths in an Engine

### ISSUE THREAD

**Issue by jrochkind** [thoughtbot/factory_bot_rails#302]
> You can configure by adding the following to "config/application.rb" or the appropriate environment configuration in "config/environments":

>      config.factory_bot.definition_file_paths = ["custom/factories"]

When I try to do this in my project (which is a Rails engine, so that may be part of the issue), I get 

    NoMethodError: undefined method `factory_bot' for #<Rails::Application::Configuration:0x00007faa177a7240>

Any ideas for how to get this to work in engine dev? The defaults are looking for factories in the engine 'dummy' app rather than the engine itself, is why I am needing to customize it.

**Comment by composerinteralia** [comment]
This configuration is new (https://github.com/thoughtbot/factory_bot_rails/pull/289) and isn't in a released version yet. I am working on a fb and fbr 5 release, but it is not quite ready.

I think https://github.com/thoughtbot/factory_bot_rails/pull/149/files is how people used to do this.

**Comment by jrochkind** [comment]
Ah right, I forgot about being careful about looking at master README. 

Thanks, that link is helpful.  You might still get a "double" load doing it that way. Maybe. I haven't figured out how/the place to intervene to actually _replace_ factory_bot_rails' defaults _before_ it loads factories from them. 

Hopefully your new code takes that into account, including in engine context, glad you were already working on improvements here!

**Comment by composerinteralia** [comment]
Yup, the new configuration should work fine in an engine. I'll close this for now, but once version 5 is out, we can open another issue if there are any problems.
