### ISSUE TITLE
Undefined method `build' for main:Object

### ISSUE THREAD

**Issue by Gusarov2k** [thoughtbot/factory_bot_rails#309]
Hello! Please help understand what the reason is that the method build does not work. I was looking for similar errors in Google, but the proposed options did not help me. Thanks for your help. )
```
context 'when update card' do
    let(:card) { build(:card) }

    before do
      visit edit_card_path(card)
    end
```
or console

```
pry(main)> card = build(:card)
NoMethodError: undefined method `build' for main:Object
from (pry):4:in `__pry__'
```

spec/rails_helper.rb
```
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../config/environment', __dir__)
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'
require 'capybara/rails'
require 'spec_helper'
require 'support/factory_bot'

begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  puts e.to_s.strip
  exit 1
end

RSpec.configure do |config|
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = true
  config.infer_spec_type_from_file_location!
  config.filter_rails_from_backtrace!
end

Capybara.register_driver(:firefox) do |app|
  Capybara::Selenium::Driver.new(
    app,
    browser: :remote,
    url: ENV.fetch('SELENIUM_URL'),
    desired_capabilities: Selenium::WebDriver::Remote::Capabilities.firefox
  )
end

```
spec/support/factory_bot.rb
```
require 'factory_bot'

RSpec.configure do |config|
 config.include FactoryBot::Syntax::Methods
  config.before(:all) do
   FactoryBot.reload
  end
end

```
spec/factories/cards.rb
```
FactoryBot.define do
  factory :card do
    original_text   { 'home' }
    translated_text { 'дом' }
  end
end
```
spec/spec_helper.rb
```
require 'simplecov'
SimpleCov.start
require 'capybara/rspec'

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
  config.shared_context_metadata_behavior = :apply_to_host_groups
end
```

gemfile
```

group :test do
  gem 'capybara'
  gem 'factory_bot'
  gem 'selenium-webdriver'
  gem 'simplecov', require: false
end
```
ruby: 2.2.10
rails: 4.2.10

**Comment by composerinteralia** [comment]
The build method is defined on `FactoryBot`, so in the console you will need to call `FactoryBot.build`.

It does look like your spec/support/factory_bot.rb has the configuration described [here](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#configure-your-test-suite) so that you can write `build` instead of `FactoryBot.build`. Did you perhaps forget to `require "spec/rails_helper.rb"` in your test?

**Comment by Gusarov2k** [comment]
Yes I add now to spec_helper.rb
```
require 'simplecov'
SimpleCov.start
require 'capybara/rspec'
require "spec/rails_helper.rb"

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
  config.shared_context_metadata_behavior = :apply_to_host_groups
end

```
but 

```
pry(main)> card = FactoryBot.build(:card)
NameError: uninitialized constant FactoryBot
from (pry):1:in `__pry__'
```
```

pry(main)> stub = build_stubbed(:card)
NoMethodError: undefined method `build_stubbed' for main:Object
from (pry):1:in `__pry__'
```

**Comment by composerinteralia** [comment]
Actually that makes sense from the console, since you have `factory_bot` in the `test` group in your Gemfile. If you want to use it in development as well, you will need to include it in the development group.

Since you are using Rails, I would actually recommend using `factory_bot_rails` instead of `factory_bot`. As shown in https://github.com/thoughtbot/factory_bot_rails#configuration,

```rb
group :development, :test do
  gem 'factory_bot_rails'
end
```

**Comment by composerinteralia** [comment]
Also, you may now have a circular require (the rails_helper requires the spec_helper and the spec_helper requires the rails_help). I would normal have the rails_helper require the spec_helper, then require the rails_helper in the spec file (for example https://github.com/rspec/rspec-rails#model-specs)

**Comment by composerinteralia** [comment]
I'm going to close this issue, since it seems to be more of a local configuration problem, rather than a bug with factory_bot. But let me know if you have any more trouble and I will try to help!

**Comment by Gusarov2k** [comment]
Thank you so much for your help. build works. but when running tests bundle exec rspec 
 let(:card) { build(:card) }
tests down

**Comment by composerinteralia** [comment]
So `let(:card) { build(:card) }` is still failing? What is the error message?
