### ISSUE TITLE
instructions for automatically updating to dynamic attributes is incorrect 

### ISSUE THREAD

**Issue by jjb** [thoughtbot/factory_bot_rails#316]
with 4.11.1 I see:

```
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:

[snip]

To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:

rubocop \
  --require rubocop-rspec \
  --only FactoryBot/AttributeDefinedStatically \
  --auto-correct
```

when i install that and run it, i get:

```
$ rubocop --require rubocop-rspec --only FactoryBot/AttributeDefinedStatically --auto-correct
Inspecting 381 files


0 files inspected, no offenses detected
Unrecognized cop or department: FactoryBot/AttributeDefinedStatically.
Did you mean? FactoryBot/DynamicAttributeDefinedStatically, FactoryBot/StaticAttributeDefinedDynamically
```

**Comment by composerinteralia** [comment]
https://github.com/thoughtbot/factory_bot/issues/1173, perhaps?

**Comment by composerinteralia** [comment]
Also I think the cop was introduced in rubocop-rspec 1.28 so you will need to be on at least that version.

**Comment by jjb** [comment]
I have had success (i think) with these commands

```
rubocop --require rubocop-rspec --only FactoryBot/DynamicAttributeDefinedStatically --auto-correct spec/factories/*
rubocop --require rubocop-rspec --only FactoryBot/StaticAttributeDefinedDynamically --auto-correct spec/factories/*
```

they found things to correct

**Comment by jjb** [comment]
🤦‍♂️ i didin't have rubocop-rspec in my gemfile, and/or it was at 1.26. while switching around branches i accidentally removed it. i think maybe those other two commands worked because rubocop-rspec 1.26 was sitting around in some form.

closing this out. sorry for the noise, and thanks for a great project!

**Comment by jjb** [comment]
(and re that other ticket-- yes i did have to add `spec/factories/*` to the end of the command)

**Comment by composerinteralia** [comment]
I'm glad it worked ! Let me know if you have any more trouble.
