### ISSUE TITLE
new reload behavior breaks normal code reloading with Spring

### ISSUE THREAD

**Issue by jakeonfire** [thoughtbot/factory_bot_rails#323]
Whenever I change code inside the Rails app/ dir, FactoryBot no longer reloads (per the decisions in this commit: https://github.com/thoughtbot/factory_bot_rails/commit/02a0f584876ff5c7a6d6fa4965da58ed70464a73). This causes a myriad of strange errors, like having multiple class objects for models for which there exist factories (in other words, `MyModel.object_id`, and `my_model_factory_instance.class.object_id` drift apart somehow), ActiveModel methods seem to be forgotten (like `ActiveRecord#store_accessor` not defined errors), and other weirdness.

Adding back
```ruby
if defined?(Spring)
  Spring.after_fork { FactoryBot.reload }
end
```
fixes this issue (for example, in a `config.after_initalize` block in config/environments/test.rb). But this doesn't feel right at all.

I'm not sure if this has something to do with how our app is configured, but it makes using `spring` and `factory_bot_rails` 5.x (and Rails 5.2?) together a non-option (without the workaround mentioned above).

**Comment by composerinteralia** [comment]
I had a feeling this was going to be a problem when I saw https://github.com/thoughtbot/factory_bot/issues/1029#issuecomment-463413328.

We may need to swap out ` reloader.execute_if_updated` in https://github.com/thoughtbot/factory_bot_rails/blob/e1ab9a05686cb52219e38f830f5088379da59276/lib/factory_bot_rails/reloader.rb#L34 with ` reloader.execute`, so any time anything changes in the application factory_bot will reload too. This matches what the rails routes reloader does: https://github.com/rails/rails/blob/2420c44d4b1dfbffea7b624cb8a8c68beb05936f/railties/lib/rails/application/finisher.rb#L144-L154

Thanks for the issue!

**Comment by jakeonfire** [comment]
I had the same thought, but doing so seems to conflict with some other aspect of the loading architecture, yielding (for me):
Factory already registered: adapter (FactoryBot::DuplicateDefinitionError)
...which is the first factory alphabetically.
I'm sure someone can figure it out though.

**Comment by jakeonfire** [comment]
https://github.com/thoughtbot/factory_bot_rails/blob/e1ab9a05686cb52219e38f830f5088379da59276/lib/factory_bot_rails/railtie.rb#L25

**Comment by composerinteralia** [comment]
Yup, that seems like the way to go. I would love to see a failing spec for this, but I haven't actually been able to recreate it myself.

**Comment by jakeonfire** [comment]
seems to be when `gems/railties-5.2.2/lib/rails/application/finisher.rb:150` runs but not `FactoryBot.reload`.

**Comment by composerinteralia** [comment]
@jakeonfire are you working on this, or are you still interested in working on this? Let me know if I can help.

**Comment by jakeonfire** [comment]
@composerinteralia i am not. happy to submit a PR if you'd like, but i won't be able to figure out a spec around it.

**Comment by composerinteralia** [comment]
@jakeonfire Feel free to submit a PR with whatever you have (although no pressure at all), and I can try and add the test coverage.

**Comment by jakeonfire** [comment]
there are 3 failing specs where `FactoryBot.reload` gets called twice instead of once. i'm not sure why that is though.

**Comment by composerinteralia** [comment]
Fixed with https://github.com/thoughtbot/factory_bot_rails/pull/330

**Comment by jakeonfire** [comment]
thanks for your help with this!

![image](https://user-images.githubusercontent.com/68826/55834659-468ebb00-5acf-11e9-902b-59ec21a63f4f.png)
