### ISSUE TITLE
Weird validation failure with Rails 5.2.2 and factory_bot_rails 5.0.1

### ISSUE THREAD

**Issue by matssigge** [thoughtbot/factory_bot_rails#324]
I just updated from 4.11.1 to 5.0.1, and three of my specs failed. I looked at them, and couldn't understand why factory_bot would even affect them (I still can't), but I managed to reproduce the same behavior in a minimal repo. I have two models - Parent and Child - with the expected association. The spec in question just validates that the Child model is not valid without a parent. (And yes, I realize that this is not a spec you need to write, but it should still work.) The spec fails using factory_bot 5.0.1 but works with 4.11.1.

I've created a repo at [matssigge/fb_test](https://github.com/matssigge/fb_test), but the TL;DR is the following spec:

```ruby
require 'rails_helper'

RSpec.describe Child, type: :model do
  it "is not valid without parent" do
    child = build(:child)
    child.parent_id = nil
    expect(child).not_to be_valid
  end
end
```

The weird part is that if I clear the parent by setting the association, i.e. `child.parent = nil` instead of `child.parent_id = nil`, then the spec works. Like I said, I can't understand how factory_bot can affect this, but evidently it does.

I'm using Rails 5.2.2 and Ruby 2.6.1.

**Comment by composerinteralia** [comment]
Thanks for the issue! We made some changes to the way the build strategy works in `https://github.com/thoughtbot/factory_bot/commit/d0208eda9c65cbc476a02d2f7503234195610005`, and this looks like it is probably related to that. There related issue may help: https://github.com/thoughtbot/factory_bot_rails/issues/314

**Comment by matssigge** [comment]
Ah, so this is because the associated object (the parent in my case) has not been created yet (only built)? So setting `parent_id` to nil doesn't actually change anything (because child.parent.id is nil), but setting `parent` to nil is explicitly saying "I don't want to be associated with that other object anymore"?

I looked (ok, glanced) at #314 but still didn't realize that this could be the effect. So I guess this is expected behavior, and perfectly all right. I'll just close this again. Sorry for wasting time. 🙄

**Comment by composerinteralia** [comment]
This is not a waste of time at all! I appreciate the issue, and your followup.

Yes, I think this is the expected behavior now that the associations built instead of created. Using just Rails you would get the same behavior:

```rb
child = Child.new
parent = Parent.new
child.parent = parent
child.parent_id = nil
child.parent
#<Parent:0x00007ff138b07918>
```

So you are correct that `child.parent_id = nil` does nothing when `child.parent` is not persisted.
