### ISSUE TITLE
incompatible marshal file format (can't be read)

### ISSUE THREAD

**Issue by AlbertMontolio** [thoughtbot/factory_bot_rails#337]
When trying to instal factory_bot_rails, 

`gem install factory_bot_rails`

I get following error message:

```
ERROR:  While executing gem ... (TypeError)
    incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
```

In the .gemrc file I have following:

 ```
---
  1 :backtrace: false
  2 :bulk_threshold: 1000
  3 :sources:
  4 - http://gems.rubyforge.org/
  5 - http://gems.github.com
  6 - https://rubygems.org/
  7 :update_sources: true
  8 :verbose: true
  9 benchmark: false
 10 gem: "--no-document"
```

How can I solve this issue?

**Comment by composerinteralia** [comment]
Hm, I have never seen that before. I am able to run `gem install factory_bot_rails` without any problems.

I searched for the error message and saw https://stackoverflow.com/questions/54786580/error-while-executing-gem-typeerror-incompatible-marshal-file-format-can Hopefully that helps!

**Comment by composerinteralia** [comment]
@AlbertMontolio did you have any luck with this?

**Comment by AlbertMontolio** [comment]
Yes, the error was somewhere else. Thanks a lot for your time

**Comment by composerinteralia** [comment]
I'm glad it worked out. I'm going to close this issue now.
