### ISSUE TITLE
Install fewer gems on Travis

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/factory_bot_rails#370]
As discussed in https://github.com/thoughtbot/factory_bot_rails/pull/367#discussion_r399810206

Our tests generate a full rails app, but I don't think they need most of the libraries included by default. Unneeded gems make our test suite slower, and increase the chance of getting errors when new versions of each gem come out.

We may not need to include all of these libraries. Passing `--skip javascript`, for example, sped up our test suite significantly.  We may also want to pass `--skip-action-mailer`, `--skip-active-storage`, `--skip-action-cable`, etc. We could also try passing `--api`.

Additionally, we may want to explore passing `--skip bundle` and then manually running `bundle install --without development` to avoid installing unnecessary development gems.

**Comment by alextrueman** [comment]
I think we can split it into a few PRs:
1. With adding pass options(--skip-..., --api)
2. With experiments with `--skip bundle`
3. With the revision of the gems
