### ISSUE TITLE
Dead link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by buhtz** [thoughtbot/factory_bot_rails#409]
Hi,

this is about
https://github.com/thoughtbot/factory_bot_rails/blob/b149856be340f919a49bab8d4389050dce422cbc/CONTRIBUTING.md

The link to the Style Guide in there is dead.

**Comment by composerinteralia** [comment]
We could probably switch it to the top-level repo: https://github.com/thoughtbot/guides

**Comment by mathieujobin** [comment]
looks like this was solved by https://github.com/thoughtbot/factory_bot_rails/commit/57e88e79bf9d965eb4147cc111c2feff18b52c12
