### ISSUE TITLE
gemspec is missing required_ruby_version

### ISSUE THREAD

**Issue by kyrofa** [thoughtbot/factory_bot_rails#456]
Closely related to https://github.com/thoughtbot/factory_bot/issues/1614: the gemspec doesn't claim any specific Ruby compatibility, but it's pretty clear from commits like https://github.com/thoughtbot/factory_bot_rails/commit/499635fcaffd5a1701626246716a74440970f23c that only specific ones are supported. The gem will be far easier to use if the gemspec can make that clear.

**Comment by JuanVqz** [comment]
+1

**Comment by unused** [comment]
As [factory_bot defines a required Ruby version](https://github.com/thoughtbot/factory_bot/blob/main/factory_bot.gemspec#L18) and `factory_bot_rails` has a clear dependency on it, there is no need to keep it redundant with it's own Gemspec. Avoiding this also ensures the specifications can't diverge.

**Comment by kyrofa** [comment]
This gem includes Ruby code, though. It should have an opinion (and test matrix) on the Ruby versions with which its code is compatible.

**Comment by unused** [comment]
I disagree that there's any case they should diverge but I see no disadvantage of adding the minimal Ruby version as with `factory_bot` to the specification.
