### ISSUE TITLE
Fix standard errors

### ISSUE THREAD

**Issue by sarahraqueld** [thoughtbot/factory_bot_rails#474]
On Github actions:

standard: Use Ruby Standard Style (https://github.com/standardrb/standard)
  spec/support/macros/define_constant.rb:10:40: Style/ArgumentsForwarding: Use anonymous block arguments forwarding (`&`).
  spec/support/macros/define_constant.rb:11:52: Style/ArgumentsForwarding: Use anonymous block arguments forwarding (`&`).
  spec/support/macros/define_constant.rb:20:32: Style/ArgumentsForwarding: Use anonymous block arguments forwarding (`&`).
  spec/support/macros/define_constant.rb:25:43: Style/ArgumentsForwarding: Use anonymous block arguments forwarding (`&`).
standard: Run `rake standard:fix` to fix up to 4 problems.

https://github.com/thoughtbot/factory_bot_rails/actions/runs/9221161554/job/25369617245?pr=468

**Comment by smaboshe** [comment]
Nice catch!

Would it be worth adding a Standard check to our GitHub Actions?
