### ISSUE TITLE
Feature Request: Allow creation of factory from existing model

### ISSUE THREAD

**Issue by asanghi** [thoughtbot/factory_bot_rails#63]
It would be nice to allow 

``` ruby
rails g factory_girl:model Post --from-schema
```

This would read the existing Post model's attributes and generate a fixture from there instead of having to specify the attributes explicitly on the command line. The use case allows for reducing the effort a bit when moving a largish project a lot of models (with lots of attributes) to factory_girl.

Ideas? Thoughts?

**Comment by rastogiachyut** [comment]
This would be very helpful in generating some demo data!

**Comment by Randall-Coding** [comment]
Was this ever implemented?

**Comment by xofred** [comment]
> Was this ever implemented?

Sorry to say, but no. Luckily I found a [neat script](https://stackoverflow.com/a/50319158/2180787) can somehow automate the feature. But it will break if the table does not have a model definition. We better rescue that situation.
