### ISSUE TITLE
factories generated in 'test/' not 'spec/' with RSpec in 4.2.0

### ISSUE THREAD

**Issue by DanielKehoe** [thoughtbot/factory_bot_rails#88]
The behavior of factory_girl_rails has changed from 4.1.0 to 4.2.0 when used with RSpec.

Prior to 4.2.0, specifying a generator in _config/application.rb_ would create a factory file in the 'spec/factories' directory.

```
config.generators do |g|
    g.test_framework :rspec, fixture: true
    g.fixture_replacement :factory_girl
end
```

After updating to factory_girl_rails 4.2.0, the generator creates a factory file in the 'test/factories' directory.

The expected behavior can be forced by specifying the directory like this:

```
config.generators do |g|
    g.test_framework :rspec, fixture: true
    g.fixture_replacement :factory_girl, dir: "spec/factories"
end
```

I don't know whether the change in configuration requirements is intentional or whether 4.2.0 introduced an anomaly.

Here are the steps to reproduce the behavior.

$ rvm gemset create fgtest
$ rvm gemset use fgtest 
$ gem list
  **\* LOCAL GEMS ***
  bundler (1.2.3)
  rake (10.0.3)
  rubygems-bundler (1.1.0)
  rubygems-update (1.8.25)
  rvm (1.11.3.6, 1.11.3.5)
$ gem install rails
$ rails new myapp
$ cd myapp
  add factory_girl_rails 4.1.0 to the Gemfile:
  gem "factory_girl_rails", "4.1.0", :group =  [:development, :test]
$ bundle install
$ rails generate model foo
  creates test/factories/foos.rb (expected behavior)
  add rspec-rails to the Gemfile:
  gem "rspec-rails", ">= 2.12.2", :group =  [:development, :test]
$ bundle install
  edit config/application.rb to add:

```
config.generators do |g|
  g.test_framework :rspec, fixture: true
  g.fixture_replacement :factory_girl
end
```

$ rails generate model bar
  creates spec/factories/bars.rb (expected behavior with factory_girl_rails 4.1.0)
  update Gemfile from factory_girl_rails 4.1.0 to 4.2.0
  gem "factory_girl_rails", "4.2.0", :group =  [:development, :test]
$ bundle update
$ rails generate model baz
  creates test/factories/bazs.rb  (unexpected behavior with factory_girl_rails 4.2.0)
$ rails generate model baz
      invoke  active_record
      create    db/migrate/20130130201940_create_bazs.rb
      create    app/models/baz.rb
      invoke    rspec
      create      spec/models/baz_spec.rb
      invoke      factory_girl
      create        test/factories/bazs.rb
  edit config/application.rb to add:

```
    config.generators do |g|
      g.test_framework :rspec, fixture: true
      g.fixture_replacement :factory_girl, dir: "spec/factories"
    end
```

$ rails generate model qux
  creates spec/factories/quxes.rb (expected behavior)

**Comment by equivalent** [comment]
@taavo good spot
