### ISSUE TITLE
Can't use FactoryGirl with my Rails Engine

### ISSUE THREAD

**Issue by valk** [thoughtbot/factory_bot_rails#99]
Hi guys,

I opened this SO question http://stackoverflow.com/questions/15717431/rails-engine-with-rspec-and-factorygirl.

Briefly, I followed a few tutorials, and tried to change bits and pieces of my engine, but still getting " uninitialized constant GenericRecipe" error. 

The repo is here: https://github.com/valk/edible-recipe

Thank you.

**Comment by obromios** [comment]
etdsoft comment was very useful. Specifically, there is a know 'feature' of FactoryGirl that it does not define its paths in exactly the same way as rspec, so when using an engine you need to add to the rails_helper the following
```
FactoryGirl.definition_file_paths << File.join(File.dirname(__FILE__), 'factories')
FactoryGirl.find_definitions
```
assuming the helper is at engine_root/spec.
